owner: svasandani
repo: status.shailesh.codes
sites:
  - name: api.shailesh.codes
    url: https://api.shailesh.codes/health
assignees:
  - svasandani
status-website:
  cname: status.shailesh.codes
  name: Shailesh Codes
